#!/bin/bash
set -e

if [ -z "$RELAY_NETS" ]
then
  RELAY_NETS="$(ip addr show | awk '$1 == "inet" { print $2 ":" }' | xargs | sed 's/ //g')"
fi

opts=(
	dc_local_interfaces '0.0.0.0 ; ::0'
	dc_other_hostnames ''
	dc_relay_nets "${RELAY_NETS}"
	dc_eximconfig_configtype 'satellite'
	dc_readhost 'island.byu.edu'
	dc_smarthost 'mmgateway.byu.edu'
	dc_use_split_config 'true'
	dc_hide_mailname 'true'
)

/etc/exim4/set-exim4-update-conf "${opts[@]}"

#manually start supervisord
/usr/bin/supervisord -c /etc/supervisord.conf
